import type { Metadata } from "next";;
import "./globals.css";
import localFont from "next/font/local";

const workSans = localFont({
  src: [
    {
      path: "../../public/fonts/WorkSans-Italic-VariableFont_wght.ttf",
      style: "italic",
    },
    {
      path: "../../public/fonts/WorkSans-VariableFont_wght.ttf",
      style: "normal",
    }
  ],
  variable: "--font-workSans",
})

export const metadata: Metadata = {
  title: "FAQ Accordion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <title>FAQ Accordion</title>
      </head>
      <body className={`${workSans.variable} min-h-screen bg-light-pink`}>{children}</body>
    </html>
  );
}
